name: payment_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - snowflake-connector-python
      - pandas
      - requests
      - sseclient  # 👈 Add this line
